### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by xijingting** [RabbitWhite1/USTC-Health-Report#1]
我在cmd里使用pythonw.exe health_report.py没有问题。但是使用绝对路径的D:\Anaconda3\envs\py36\pythonw.exe health_report.py就没有响应了。好奇什么原因。因为任务计划添加里是绝对路径的pythonw.exe也导致 没办法启动程序。

**Comment by RabbitWhite1** [comment]
您好，正常情况下，如果你是运行install.py来设置任务的话，应该是没问题的。install.py能够自动识别pythonw.exe的位置，并用其绝对路径作为计划任务的运行程序，然后将install.py所在文件夹下的health_report.py作为pythonw的运行参数(也就是将要运行的代码)来运行。


您说使用"D:\Anaconda3\envs\py36\pythonw.exe health_report.py"没有响应，会不会是因为你没有使用health_report.py的绝对路径呢?







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RabbitWhite1/USTC-Health-Report"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月7日(星期一) 晚上8:24
收件人:&nbsp;"RabbitWhite1/USTC-Health-Report"<USTC-Health-Report@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[RabbitWhite1/USTC-Health-Report] 有个问题 (#1)





 
我在cmd里使用pythonw.exe health_report.py没有问题。但是使用绝对路径的D:\Anaconda3\envs\py36\pythonw.exe health_report.py就没有响应了。好奇什么原因。因为任务计划添加里是绝对路径的pythonw.exe也导致 没办法启动程序。
