### ISSUE TITLE
是更新了那个data对象的参数是吧？

### ISSUE THREAD

**Issue by xijingting** [RabbitWhite1/USTC-Health-Report#2]
data = {'username': username, 'password': password,
                'service': "https://weixine.ustc.edu.cn/2020/caslogin", 'model': "uplogin.jsp",
                'warn': '', 'showCode': '', 'button': ''}
以前不是通过jsp上传的吗？我是啥也不懂

**Comment by RabbitWhite1** [comment]
我没有注意，我就是抓包抄下来, 如果你明白了希望能告诉我，感谢！
